config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :chores

  root 'welcome#index'

  get 'signup' => 'users#new'

  get 'about' => 'welcome#about'

  get 'home' => 'welcome#index'

  get 'login'   => 'sessions#new'

  post   'login'   => 'sessions#create'

  delete 'logout'  => 'sessions#destroy'

  get 'contact', to: 'welcome#contact', as: 'contact'

  get 'ryan', to: 'welcome#ryan_contact', as: 'ryan'

  get 'shiva', to: 'welcome#shiva_contact', as: 'shiva'

  get 'holly', to: 'welcome#holly_contact', as: 'holly'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :chores, dependent: :destroy
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # Returns the hash digest of the given string.
  # def User.digest(string)
  # cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  #            BCrypt::Engine.cost
  # BCrypt::Password.create(string, cost: cost)
  #end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update, :show]
  before_action :is_admin, only: [:index, :delete]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    set_user
    @chores = @user.chores.paginate(page: params[:page], per_page: 5)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    set_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        add_chores
        if Chore.create(@chores)
          log_in @user
          format.html { redirect_to @user, notice: 'Sign-up was successful.' }
          format.json { render :show, status: :created, location: @user }
        end
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: @user.name + ' was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    set_user
    @destroyeduser = @user.name
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: @destroyeduser + ' was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:notice] = 'Please Login First'
      redirect_to login_url
    end
  end

  # Confirms a logged-in user.
  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user) || is_admin?
      flash[:notice] = 'Unauthorized Access'
      redirect_to(root_url)
    end
  end

  # Confirms if user is admin
  def is_admin
    unless is_admin?
      flash[:notice] = 'Unauthorized Access'
      redirect_to root_url
    end
  end

  # Adds Default Chores to a new user
  def add_chores()
    @chores = add_default_chores(@user.id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 200 })
    gravatar_id = user.id * 25
    size = options[:size]
    gravatar_url = "https://i.picsum.photos/id/#{gravatar_id}/#{size}/#{size}.jpg"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :password  %>
    <%= form.password_field :password, id: :password, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, "Confirmation" %>
    <%= form.password_field :password_confirmation, id: :password_confirmation, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Create my account", class: "btn btn-lg btn-primary"  %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Settings") %>
<div class="center jumbotron">
  <h1>Update your profile</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!-- Users Page -->
<% provide(:title, "Users - Index") %>
<div class="center jumbotron" id="users">
  <p id="notice"><%= notice %></p>

  <h1>Users</h1>
  <div class="center">
    <table>
      <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New User', new_user_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>

app/views/users/new.html.erb
<!-- Sign Up Page -->
<% provide(:title, "Sign Up") %>
<div class="center jumbotron" id="signup">
  <h1>Sign up</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form', user: @user %>
      <br>
      <p>Current User? <%= link_to "Login Now!", login_path, :class => "btn btn-success" %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- You're Signed In -->
<% provide(:title, @user.name ) %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= gravatar_for @user %>
        <p id="notice"><%= notice %></p>
      </section>
    </aside>
    <aside class="col-md-4 spacing">
      <div>
        <h3>User Information</h3>
      </div>
      <div>
        <strong>Name:</strong>
        <%= @user.name %>
      </div>
      <div>
        <strong>Email:</strong>
        <%= @user.email %>
      </div>
      <div>
        <strong>Time:</strong>
        <%= Time.now %>
      </div>
    </aside>
    <div class="col-md-4">
      <% if @user.chores.any? %>
        <h3>Chores (<%= @user.chores.count %>)</h3>
        <ol class="chores">
          <%= render @chores %>
        </ol>
        <%= will_paginate @chores %>
      <% end %>
    </div>
  <div class="row">
    <div class="center">
      <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-lg btn-primary" %> |
      <%= link_to 'Back', users_path, class: "btn btn-lg btn-primary" %>
    </div>
  </div>
</div>