config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :chores

  root 'welcome#index'

  get 'signup' => 'users#new'

  get 'about' => 'welcome#about'

  get 'home' => 'welcome#index'

  get 'login'   => 'sessions#new'

  post   'login'   => 'sessions#create'

  delete 'logout'  => 'sessions#destroy'

  get 'contact', to: 'welcome#contact', as: 'contact'

  get 'ryan', to: 'welcome#ryan_contact', as: 'ryan'

  get 'shiva', to: 'welcome#shiva_contact', as: 'shiva'

  get 'holly', to: 'welcome#holly_contact', as: 'holly'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def contact
  end
  def ryan_contact
  end
  def shiva_contact
  end
  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<!-- About Page -->
<% provide(:title, "About") %>
<div class="container center" id="about">
  <div>
    <h1>What can Chore Bucks do for you?</h1>
    <hr class="divider light my-4">
  </div>
  <div>
    <p>Chore Bucks is a Home Organization web-application for Families!<br><br>The Adult family member can create Chores for the children to accomplish; assigning the chores each with a Title, Description, Completion Date, Complexity, and Dollar Price.
    <br><br>The Child will then be able to “Add Chore to Cart,” “Complete Chore,” and “Request Payment.” <br><br>The Admin family member will be notified that a Child is requesting payment, after verifying that the chore has been done, the admin can “Approve Payment” to add funds to a Child’s Account.<br><br>Overall, Chore Bucks wants to help Families maintain a Happy, Fun, and Clean Home!</p>
    <p><%= link_to "Sign up Now!", signup_path, :class => "btn btn-primary" %></p>
  </div>
</div>

app/views/welcome/contact.html.erb
<!-- Contact Page -->
<% provide(:title, "Contact") %>
  <div class="container center" id="contact">
    <h1>Meet Our Developers</h1>
    <div>
      <hr class="divider my-4">
      <p>Peek around our Bios or Reach Out!</p>
    </div>
    <div class="row">
      <div>
        <%= link_to "Ryan Hafer", ryan_path %>
      </div>
      <div>
        <%= link_to "Shiva Acharya", shiva_path %>
      </div>
      <div>
        <%= link_to "Holly Robertson", holly_path %>
      </div>
    </div>
  </div>

app/views/welcome/holly_contact.html.erb
<!-- Holly Contact Page -->
<% provide(:title, "Holly") %>
<div class="container center" id="holly">
  <h1>Holly Robertson</h1>
  <hr class="divider my-4">
  <div class="container">
    <div>
        I am a current student at Franklin University. I'm pursuing a Bachelor's Degree in Computer Science with a minor in Web Development.
    </div>
    <br>
    <div>
      I work at Safelite as a Service Desk Analyst and am the Project Lead of this Chore Bucks Project.
    </div>
  </div>
  <div class="row">
    <div>
      (401) 375-2428
    </div>
    <div>
      <a class="d-block" href="callow16@email.franklin.edu">
        callow16@email.franklin.edu
      </a>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<!-- Welcome Page -->
<% provide(:title, "Welcome") %>
<div class="center">
  <p class="<%= set_font_color(notice) %>"><%= notice %></p>
</div>
<div class="container center" id="welcome">
  <div>
    <h1 class="text-white font-weight-bold">Chore Bucks</h1>
    <hr class="divider my-4">
  </div>
  <div>
    <p>Chore Bucks is a Home Organization web-application for Families!</p>
    <a class="btn btn-info btn-xl js-scroll-trigger" href="about">Find Out More</a>
  </div>
</div>

app/views/welcome/ryan_contact.html.erb
<!-- Ryan Contact Page -->
<% provide(:title, "Ryan") %>
<div class="container center" id="ryan">
  <h1>Ryan Hafer</h1>
  <hr class="divider my-4">
  <div class="container">
    <div>
      Hi there, I am Ryan Hafer, a student of Computer Science at Franklin
      My goal is to become a professional software developer
    </div>
    <br>
    <div>
      Currently I am employed at Nationwide Children's Hospital as an IS Support Technician.
      Even though I do not get to work directly with patients, it brings me some joy that I
      get to be a small part of improving their outcomes.
    </div>
  </div>
  <div class="row">
    <div>
      (614) 984 - 8627
    </div>
    <div>
      <a class="d-block" href="hafer02@email.franklin.edu">
        hafer02@email.franklin.edu
      </a>
    </div>
  </div>
</div>

app/views/welcome/shiva_contact.html.erb
<!-- Shiva Contact Page -->
<% provide(:title, "Holly") %>
<div class="container center" id="shiva">
  <h1>Shiva Acharya</h1>
  <hr class="divider my-4">
  <div class="container">
    <div>
      My name is Shiva Acharya. I'm currently pursuing Bachelors of Science in Computer Science from Franklin University.
      I hope to finish my courseworks by the end of Summer semester. My hobbies include listening to musics, reading books,
      and playing ping pong with my little sister.
    </div>
    <br>
    <div>
      I work at Cerotid as a Junior Java Developer. I'm one of the developers of this Chore Bucks Project.
    </div>
  </div>
  <div class="row">
    <div>
      (469) 726-8172
    </div>
    <div>
      <a class="d-block" href="achary06@email.franklin.edu">
      </a>
    </div>
  </div>
</div>