config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :chores

  root 'welcome#index'

  get 'signup' => 'users#new'

  get 'about' => 'welcome#about'

  get 'home' => 'welcome#index'

  get 'login'   => 'sessions#new'

  post   'login'   => 'sessions#create'

  delete 'logout'  => 'sessions#destroy'

  get 'contact', to: 'welcome#contact', as: 'contact'

  get 'ryan', to: 'welcome#ryan_contact', as: 'ryan'

  get 'shiva', to: 'welcome#shiva_contact', as: 'shiva'

  get 'holly', to: 'welcome#holly_contact', as: 'holly'

end

app/models/chore.rb
class Chore < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 25 }
  validates :description, length: { maximum: 255 }
  validates :price, presence: true
  validates :difficultyLvl, presence: true, length: { maximum: 1 }
  validates :completeBy, presence: true
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  # GET /chores
  # GET /chores.json
  def index
    find_chores
  end

  # GET /users/1
  # GET /users/1.json
  def show
    redirect_to action: "index"
  end

# GET /chores/new
  def new
    @user = User.find_by(id: session[:user_id])
    @chore = Chore.new(user_id: @user.id)
  end

  # GET /users/1/edit
  def edit
    set_chore
  end

# POST /users
# POST /users.json
  def create
    @chore = Chore.new(chore_params)
    respond_to do |format|
      if @chore.save
        format.html { redirect_to @chore, notice: 'Chore was created.' }
        format.json { render :index, status: :created, location: @chore }
      else
        format.html { render :new }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chores/1
  # PATCH/PUT /chores/1.json
  def update
    set_chore
    respond_to do |format|
      if @chore.update(update_chore_params)
        format.html { redirect_to @chore, notice: @chore.title + ' was successfully updated.' }
        format.json { render :show, status: :ok, location: @chore }
      else
        format.html { render :edit }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    set_chore
    @destroyedchore = @chore.title
    @chore.destroy
    respond_to do |format|
      format.html { redirect_to chores_url, notice: @destroyedchore + ' was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

# Only allow a list of trusted parameters through.
  def chore_params
    params.require(:chore).permit(:user_id, :title, :description, :price, :difficultyLvl,
                                 :completeBy, :isFunded, :isAvailable)
  end

  # Only allow a list of trusted parameters through.
  def update_chore_params
    params.require(:chore).permit(:user_id, :title, :description, :price, :difficultyLvl,
                                  :completeBy, :isFunded, :isAvailable, :isCheckedOut, :isCompleted,
                                  :isApproved, :isPaid)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_chore
    @chore = Chore.find(params[:id])
  end

  def find_chores
    @user = User.find_by(id: session[:user_id])
    @chores = Chore.where(:user_id => "#{@user.id}" )
  end

end

app/helpers/chores_helper.rb
module ChoresHelper
  #Formats Due Date
  def due_date(chore)
    Date.parse(chore.completeBy.to_s).strftime("%B %e, %Y")
  end

  #Sets Border Color based on Availability
  def border_class(chore)
    if chore.isCheckedOut == true
      "orange"
    elsif chore.isCheckedOut == false
      "green"
    else
      "red"
    end
  end

  #Adds a list of Chores to a new user
  def add_default_chores(user_id)
    current_date = Time.now
    two_weeks = (2*7*24*60*60)
    @chores = [
        {
            user_id: user_id,
            title: "Clean Bathroom",
            description: "Clean the bathroom. Example: Clean toilet, sink(s), bathtub, shower, mirror(s), counter(s), sweep and mop floors, and stock inventory. ",
            price: 10,
            difficultyLvl: 5,
            completeBy: current_date + two_weeks,
            isFunded: false,
            isAvailable: false,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Sweep Kitchen",
            description: "Sweep the kitchen floors",
            price: 2,
            difficultyLvl: 2,
            completeBy: current_date + two_weeks,
            isFunded: false,
            isAvailable: false,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Mop Kitchen",
            description: "Mop the kitchen floors",
            price: 3,
            difficultyLvl: 3,
            completeBy: current_date + two_weeks,
            isFunded: false,
            isAvailable: false,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Vacuum House",
            description: "Vacuum all the carpet in the house",
            price: 10,
            difficultyLvl: 3,
            completeBy: current_date + two_weeks,
            isFunded: false,
            isAvailable: false,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Vacuum Living Room",
            description: "Vacuum the floors in the living room",
            price: 2,
            difficultyLvl: 3,
            completeBy: current_date + two_weeks,
            isFunded: false,
            isAvailable: false,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Clean Room",
            description: "Clean your own room. Example: Make your bed, vacuum your room, pickup and put all out-of-place items in their proper place, clean and organize tables and/or desks. ",
            price: 5,
            difficultyLvl: 4,
            completeBy: current_date + two_weeks,
            isFunded: false,
            isAvailable: false,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Dust House",
            description: "Dust all shelves and tables in the house",
            price: 9,
            difficultyLvl: 1,
            completeBy: current_date + two_weeks,
            isFunded: false,
            isAvailable: false,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Clean Kitchen",
            description: "Clean the dishes, tables, appliances, and counters",
            price: 15,
            difficultyLvl: 4,
            completeBy: current_date + two_weeks,
            isFunded: false,
            isAvailable: false,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Laundry",
            description: "Wash, Dry and put-up all the laundry",
            price: 20,
            difficultyLvl: 5,
            completeBy: current_date + two_weeks,
            isFunded: true,
            isAvailable: true,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Clean Living Room",
            description: "Pickup the Living Room. Example: Fold all blankets, pickup and put all
                  out-of-place items in their proper place, and put the remote control in a central place.",
            price: 5,
            difficultyLvl: 1,
            completeBy: current_date + two_weeks,
            isFunded: false,
            isAvailable: false,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Disinfect House",
            description: "Use disinfectant wipes or spray to clean doorknobs, refrigerator doors, and cabinet handles",
            price: 7,
            difficultyLvl: 2,
            completeBy: current_date + two_weeks,
            isFunded: false,
            isAvailable: true,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Clean Garage",
            description: "Organize, Clean and sweep garage",
            price: 18,
            difficultyLvl: 5,
            completeBy: current_date + two_weeks,
            isFunded: true,
            isAvailable: true,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Empty Trash Cans ",
            description: "Empty all trash cans in house and put new trash bags in trash cans",
            price: 7,
            difficultyLvl: 2,
            completeBy: current_date + two_weeks,
            isFunded: true,
            isAvailable: true,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Fold Laundry",
            description: "Fold and put in all laundry in its proper place.",
            price: 10,
            difficultyLvl: 5,
            completeBy: current_date + two_weeks,
            isFunded: true,
            isAvailable: true,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Make Beds",
            description: "Make all the beds in the house properly.",
            price: 5,
            difficultyLvl: 3,
            completeBy: current_date + two_weeks,
            isFunded: true,
            isAvailable: true,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Help Cook",
            description: "Wash and cut all vegetables and be helpful to parent.",
            price: 10,
            difficultyLvl: 4,
            completeBy: current_date + two_weeks,
            isFunded: true,
            isAvailable: true,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Clean Shower",
            description: "Clean the tub and shower walls. Put all products in place and clean all shower curtains.",
            price: 9,
            difficultyLvl: 3,
            completeBy: current_date + two_weeks,
            isFunded: true,
            isAvailable: true,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Garden Work",
            description: "Rake and bag leaves, water plants/flowers, and pick up all trash.",
            price: 20,
            difficultyLvl: 5,
            completeBy: current_date + two_weeks,
            isFunded: true,
            isAvailable: true,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Feed Pets",
            description: "Clean pets water/food bowls and place new food and water in their bowls.",
            price: 2,
            difficultyLvl: 3,
            completeBy: current_date + two_weeks,
            isFunded: true,
            isAvailable: true,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Organize Books",
            description: "Organize and dust all bookshelves",
            price: 5,
            difficultyLvl: 1,
            completeBy: current_date + two_weeks,
            isFunded: true,
            isAvailable: true,
            isCheckedOut: false,
            isCompleted: false,
            isApproved: false,
            isPaid: false,
        },
        {
            user_id: user_id,
            title: "Load Dishwasher",
            description: "Load dirty dishes, add soap and run dishwasher.",
            price: 8,

app/views/chores/_chore.html.erb
<li>
  <%= image_tag chore.title.downcase, height: 50, class: border_class(chore) %>
  <span class="title"><%= link_to chore.title, chore.user %></span>
  <span class="user"><%= link_to "Parent #{chore.user.name}", chore.user %></span>
  <span class="user">Due: <%= due_date(chore) %></span>
 </li>

app/views/chores/_form.html.erb
<%= form_with(model: chore, local: true) do |form| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :user_id, class: 'form-control', readonly: true %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description  %>
    <%= form.text_area :description, id: :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :price  %>
    <%= form.text_field  :price, id: :price, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :difficultyLvl  %>
    <%= form.number_field  :difficultyLvl, id: :difficultyLvl, class: 'form-control', in: 1..5, step: 1 %>
  </div>

  <div class="field">
    <%= form.label :completeBy %>
    <%= form.date_field  :completeBy, id: :completeBy, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :isFunded, "Do you want to Fund this chore?" %>
    <%= form.select(:isFunded, [['Yes', true], ['No', false]]) %>
  </div>

  <div class="field">
    <%= form.label :isAvailable, "Do you want to make this chore Available?" %>
    <%= form.select(:isAvailable, [['Yes', true], ['No', false]]) %>
  </div>

  <div class="actions">
    <%= form.submit "Create my Chore", class: "btn btn-lg btn-primary"  %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<% provide(:title, "Settings") %>
<div class="center jumbotron">
  <h1>Edit a chore</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@chore) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :user_id %>
        <%= f.text_field :user_id, class: 'form-control', :readonly => true %>

        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control', size: "24x6" %>

        <%= f.label :price %>
        <%= f.text_field :price, class: 'form-control' %>

        <%= f.label :difficultyLvl %>
        <%= f.number_field :difficultyLvl, class: 'form-control', in: 1..5, step: 1 %>

        <%= f.label :completeBy %>
        <%= f.date_field  :completeBy, class: 'form-control'%>

        <%= f.label :isFunded, "Do you want to Fund this chore?"  %>
        <%= f.select(:isFunded, [['Yes', true], ['No', false]]) %>

        <%= f.label :isAvailable, "Do you want to make this chore Available?"  %>
        <%= f.select(:isAvailable, [['Yes', true], ['No', false]]) %>

        <%= f.label :isCheckedOut, "Is this chore Checked-Out?"  %>
        <%= f.select(:isCheckedOut, [['Yes', true], ['No', false]]) %>

        <%= f.label :isCompleted, "Is this chore Completed?"  %>
        <%= f.select(:isCompleted, [['Yes', true], ['No', false]]) %>

        <%= f.label :isApproved, "Is payment Approved?"  %>
        <%= f.select(:isApproved, [['Yes', true], ['No', false]]) %>

        <%= f.label :isPaid, "Has this chore been Paid?"  %>
        <%= f.select(:isPaid, [['Yes', true], ['No', false]]) %>

        <%= f.submit "Save changes", class: 'btn btn-primary', :readonly => true %>
      <% end %>
    </div>
  </div>
</div>

app/views/chores/index.html.erb
<!-- Users Page -->
<% provide(:title, "Chores - Index") %>
<div class="center jumbotron" id="users">
  <p id="notice"><%= notice %></p>

  <h1>Chores</h1>
  <div class="center">
    <table>
      <thead>
      <tr>
        <th>User ID</th>
        <th>Title</th>
        <th>Price</th>
        <th>Difficulty Level</th>
        <th>Availability</th>
        <th colspan="3">Admin Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @chores.each do |chore| %>
        <tr>
          <td><%= chore.user_id %></td>
          <td><%= chore.title %></td>
          <td><%= chore.price %></td>
          <td><%= chore.difficultyLvl %></td>
          <% if chore.isAvailable == false %>
            <td>Not Available</td>
          <% else %>
            <td>Is Available</td>
          <% end %>
          <td><%= link_to 'Show', chore %></td>
          <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
          <td><%= link_to 'Destroy', chore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Chore', new_chore_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>

app/views/chores/new.html.erb
<!-- Create Chore Page -->
<% provide(:title, "Create Chore") %>
<div class="center jumbotron" id="signup">
  <h1>Create Chore</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form', chore: @chore %>
      <br>
    </div>
  </div>
</div>